spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8080
  error:
    path: /error
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240
---
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .html
  config:
    activate:
      on-profile: production

