spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: mail.javaclass.online
    port: 2525
    username: lms@javaclass.online
server:
  port: 8080
  error:
    path: /error
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240
app:
  files:
    localStorage: files
  host: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: mail.javaclass.online
    port: 2525
    username: noreply.lms@javaclass.online
server:
  port: 8080
  error:
    path: /error
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240
app:
  host: http://185.203.153.109
