/*
DROP TABLE IF EXISTS requests;
*/

CREATE TABLE IF NOT EXISTS requests(
 id                 BIGSERIAL PRIMARY KEY NOT NULL,
 status				CHARACTER VARYING (60),
 is_deleted			BOOLEAN NOT NULL DEFAULT FALSE
 );